// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4kHBtxf1ZsuPR9tQLxu1aUA1BPCFoI9s',
    appId: '1:1036456782368:web:51f8633cde2c508a1a6a45',
    messagingSenderId: '1036456782368',
    projectId: 'revibe-d6266',
    authDomain: 'revibe-d6266.firebaseapp.com',
    storageBucket: 'revibe-d6266.appspot.com',
    measurementId: 'G-5S0T4C0SDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzLMF0x_cvk-FJMoiojX8iOO5Xf7DFiz4',
    appId: '1:1036456782368:android:91669dfd058007931a6a45',
    messagingSenderId: '1036456782368',
    projectId: 'revibe-d6266',
    storageBucket: 'revibe-d6266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnlrD8Kw7nv94xhpghIZhXNwdJuNSw-HA',
    appId: '1:1036456782368:ios:9215cab0f65e91bc1a6a45',
    messagingSenderId: '1036456782368',
    projectId: 'revibe-d6266',
    storageBucket: 'revibe-d6266.appspot.com',
    iosBundleId: 'com.example.revibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnlrD8Kw7nv94xhpghIZhXNwdJuNSw-HA',
    appId: '1:1036456782368:ios:67ea0a82128334231a6a45',
    messagingSenderId: '1036456782368',
    projectId: 'revibe-d6266',
    storageBucket: 'revibe-d6266.appspot.com',
    iosBundleId: 'com.example.revibe.RunnerTests',
  );
}
